name: update-stable

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  update-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to stable branch
      run: |
        git pull
        git checkout stable
        git merge master -m "merge master"
        git push
